# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [ ]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
#todo: 

import numpy as np

array_numeros = np.arange(10)  # crea un array con los números del 0 al 9 usando arange

print("Nums del 0 al 9", array_numeros)  # imprimir el array 


[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
#todo:

import numpy as np  

array_ceros = np.zeros(5)  # crea un array  con todos los elementos son 0

array_ceros[2] = 5  # cambia el tercer elemento (índice 2) a 5

print(array_ceros)  # muestra el array actualizado por consola


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [ ]:
#todo: 

import numpy as np
from random import randint
#  matriz 3x3 de números aleatorios entre 0 y 1
matriz_aleatoria = np.random.rand(3, 3)

#np.random.rand genera valores aleatorios con una distribución uniforme entre 0 y 1.

# imprimir  la matriz
print(matriz_aleatoria)


[[0.10842217 0.75474527 0.15991902]
 [0.69730411 0.32253553 0.34768626]
 [0.43218268 0.16349066 0.45369386]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [ ]:
#todo:

import numpy as np
import random

# crear el array
array = np.array([10, 20, 30, 40, 50])

# sumar 5 a cada elemento
array_sumado = array + 5

# ultiplicar por un número aleatorio 
numero_aleatorio = random.uniform(1, 10)  # genera un número aleatorio entre 1 y 10
array_multiplicado = array_sumado * numero_aleatorio

print("Array original:", array)
print("Array después de sumar 5:", array_sumado)
print("Array después de multiplicar por {numero_aleatorio}:", array_multiplicado)


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#todo:

import numpy as np

# crear una matriz de 4x4
matriz_identidad = np.eye(4)

# np.eye crea una matriz identidad de tamaño 4x4

print("matriz:", matriz_identidad) # imprimir la matriz identidad


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares y luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [3]:
#todo: 


import numpy as np

array_par = np.arange(0, 21, 2)

#arange crea un array con números desde 0 hasta 20, con un paso de 2 (números pares)

# mostrar el array de números pares
print("array de números pares:", array_par)


# sumar 5 a cada elemento 
suma = array_par + 5

#restar 3 a cada elemento 
resta = array_par - 3

# multiplicar por 2 cada elemento 
multiplicaacion = array_par * 2

# dividir entre 2 cada elemento 
division = array_par / 2

# mostrar los resultados de las operaciones
print("Array con suma de  5:", suma)
print("Array con resta de 3:", resta)
print("Array con multiplicación  por 2:", multiplicaacion)
print("Array  con division entre 2:", division)


array de números pares: [ 0  2  4  6  8 10 12 14 16 18 20]
Array con suma de  5: [ 5  7  9 11 13 15 17 19 21 23 25]
Array con resta de 3: [-3 -1  1  3  5  7  9 11 13 15 17]
Array con multiplicación  por 2: [ 0  4  8 12 16 20 24 28 32 36 40]
Array  con division entre 2: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
